[package]
name = "server"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[profile.release]
strip = true
lto = "fat"

[dependencies]
tokio = { version = "1.24.2", features = ["full"] }
futures-util = "0.3.25"
warp = "0.3.3"
tonic = "0.8.3"
tonic-reflection = "0.6.0"
prost = "0.11.6"
serde = { version = "1.0.152", features = ["derive"] }
toml = "0.6.0"

# Database
diesel = { version = "2.0.0", features = ["sqlite"] }
dotenvy = "0.15"

[build-dependencies]
tonic-build = "0.8"

[dev-dependencies]
tempfile = "3.3.0"
