name: docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: "harry1453"
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker BuildX
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Enable Buildkit caches
      uses: actions/cache@v3
      with:
        path: /tmp/buildkit-cache/buildkit-state.tar
        key: ${{ runner.os }}-buildx-${{ github.ref }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ github.ref }}
          ${{ runner.os }}-buildx-
    - name: Load Buildkit state from cache
      uses: dashevo/gh-action-cache-buildkit-state@v1
      with:
        builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
        cache-path: /tmp/buildkit-cache
        cache-max-size: 3g
    - name: Docker Build
      uses: docker/build-push-action@v3
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: "harry1453/es1-server:latest"
        cache-from: type=gha
        cache-to: type=gha,mode=max
