name: rpi-app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  
defaults:
  run:
    working-directory: rpi-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc-arm-linux-gnueabihf qemu-user-static protobuf-compiler
          execute_install_scripts: true
      - name: Configure Cross-compiler
        run: |
          rustup target add arm-unknown-linux-musleabihf
          echo "[target.arm-unknown-linux-musleabihf]" > ~/.cargo/config.toml
          echo "linker = \"arm-linux-gnueabihf-gcc\"" >> ~/.cargo/config.toml
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose
