name: server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  
defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "server"
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v2
    - name: Enable buildkit cache
      uses: actions/cache@v2
      with:
        path: /tmp/buildkit-cache/buildkit-state.tar
        key: ${{ runner.os }}-buildkit-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildkit-
    - name: Load buildkit state from cache
      uses: dashevo/gh-action-cache-buildkit-state@v1
      with:
        builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
        cache-path: /tmp/buildkit-cache
        cache-max-size: 2g
    - name: Docker Build
      uses: docker/build-push-action@v3
      with:
        context: server/
        push: false
        tags: "harry1453/es1-server:latest"
        cache-from: type=gha
        cache-to: type=gha,mode=max
